<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2019-10-12" />

<title>Budweiser Case Study</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Github Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">About Me</a>
</li>
<li>
  <a href="Budwesier-Case-Study.html">Budwesier Case Study</a>
</li>
<li>
  <a href="Attrition-Predition-Model.html">Case Study 02 DDS</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Budweiser Case Study</h1>
<h4 class="date">10/12/2019</h4>

</div>


<div id="msds-6303-doing-data-science---case-study-01" class="section level2">
<h2>MSDS 6303: Doing Data Science - Case Study 01</h2>
<p>Introduction: The purpose of the project is to present an analysis of the beer industry, then create a decision matrix that assists with chosing an expansion plan based on three options: 1) Buy an current brewery, 2) Build a new brewery, or 3)Expand current production levels. Since our data is based on historical information, we will assume precendent for our future assumption of establishing an “ideal” targeted location to allocate resources for expansion.</p>
<pre class="r"><code>##Install and load necessary libraries 

library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------------------------------------------------------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.2.1     v purrr   0.3.2
## v tibble  2.1.3     v dplyr   0.8.3
## v tidyr   1.0.0     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.4.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------------------------------------------------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(readr)
library(dplyr)
library(stringr)
library(DataExplorer)
library(class)
library(caret)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre class="r"><code>library(maps)</code></pre>
<pre><code>## 
## Attaching package: &#39;maps&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     map</code></pre>
<pre class="r"><code>library(knitr)
library(corrplot)</code></pre>
<pre><code>## corrplot 0.84 loaded</code></pre>
<pre class="r"><code>##Importing the data

Beers &lt;- read_csv(&quot;C:/Users/Antonio Debouse/Desktop/Doing Data Science/GitHub/Budweiser-Case-Study/Budweiser Case Study/Beers.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Name = col_character(),
##   Beer_ID = col_double(),
##   ABV = col_double(),
##   IBU = col_double(),
##   Brewery_id = col_double(),
##   Style = col_character(),
##   Ounces = col_double()
## )</code></pre>
<pre class="r"><code>str(Beers)</code></pre>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 2410 obs. of  7 variables:
##  $ Name      : chr  &quot;Pub Beer&quot; &quot;Devil&#39;s Cup&quot; &quot;Rise of the Phoenix&quot; &quot;Sinister&quot; ...
##  $ Beer_ID   : num  1436 2265 2264 2263 2262 ...
##  $ ABV       : num  0.05 0.066 0.071 0.09 0.075 0.077 0.045 0.065 0.055 0.086 ...
##  $ IBU       : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ Brewery_id: num  409 178 178 178 178 178 178 178 178 178 ...
##  $ Style     : chr  &quot;American Pale Lager&quot; &quot;American Pale Ale (APA)&quot; &quot;American IPA&quot; &quot;American Double / Imperial IPA&quot; ...
##  $ Ounces    : num  12 12 12 12 12 12 12 12 12 12 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   Name = col_character(),
##   ..   Beer_ID = col_double(),
##   ..   ABV = col_double(),
##   ..   IBU = col_double(),
##   ..   Brewery_id = col_double(),
##   ..   Style = col_character(),
##   ..   Ounces = col_double()
##   .. )</code></pre>
<pre class="r"><code>view(Beers)

Breweries &lt;- read_csv(&quot;C:/Users/Antonio Debouse/Desktop/Doing Data Science/GitHub/Budweiser-Case-Study/Budweiser Case Study/Breweries.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Brew_ID = col_double(),
##   Name = col_character(),
##   City = col_character(),
##   State = col_character()
## )</code></pre>
<pre class="r"><code>str(Breweries)</code></pre>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 558 obs. of  4 variables:
##  $ Brew_ID: num  1 2 3 4 5 6 7 8 9 10 ...
##  $ Name   : chr  &quot;NorthGate Brewing&quot; &quot;Against the Grain Brewery&quot; &quot;Jack&#39;s Abby Craft Lagers&quot; &quot;Mike Hess Brewing Company&quot; ...
##  $ City   : chr  &quot;Minneapolis&quot; &quot;Louisville&quot; &quot;Framingham&quot; &quot;San Diego&quot; ...
##  $ State  : chr  &quot;MN&quot; &quot;KY&quot; &quot;MA&quot; &quot;CA&quot; ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   Brew_ID = col_double(),
##   ..   Name = col_character(),
##   ..   City = col_character(),
##   ..   State = col_character()
##   .. )</code></pre>
<pre class="r"><code>view(Breweries)

summary(Breweries)</code></pre>
<pre><code>##     Brew_ID          Name               City              State          
##  Min.   :  1.0   Length:558         Length:558         Length:558        
##  1st Qu.:140.2   Class :character   Class :character   Class :character  
##  Median :279.5   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :279.5                                                           
##  3rd Qu.:418.8                                                           
##  Max.   :558.0</code></pre>
<pre class="r"><code>##Initial Brewery Data Analysis

plot_missing(Breweries)</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>#Questions 1: How many breweries are present in each state?
##Calculate the number of breweries
summary(Breweries$State)</code></pre>
<pre><code>##    Length     Class      Mode 
##       558 character character</code></pre>
<pre class="r"><code>#Seperate Brewery count by States
StateCount = count(Breweries,Breweries$State)


##Change &quot;n&quot; to column name &quot;Number of Brewiers in State&quot;
colnames(StateCount)[1]=&quot;State_ABV&quot;
colnames(StateCount)[2]=&quot;Number of Breweries in State&quot;

str(StateCount)</code></pre>
<pre><code>## Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:    51 obs. of  2 variables:
##  $ State_ABV                   : chr  &quot;AK&quot; &quot;AL&quot; &quot;AR&quot; &quot;AZ&quot; ...
##  $ Number of Breweries in State: int  7 3 2 11 39 47 8 1 2 15 ...</code></pre>
<pre class="r"><code>view(StateCount)

##Arrange States in descending order base on number of breweries
arrange(StateCount,desc(StateCount$`Number of Breweries in State`))</code></pre>
<pre><code>## # A tibble: 51 x 2
##    State_ABV `Number of Breweries in State`
##    &lt;chr&gt;                              &lt;int&gt;
##  1 CO                                    47
##  2 CA                                    39
##  3 MI                                    32
##  4 OR                                    29
##  5 TX                                    28
##  6 PA                                    25
##  7 MA                                    23
##  8 WA                                    23
##  9 IN                                    22
## 10 WI                                    20
## # ... with 41 more rows</code></pre>
<pre class="r"><code>##Plot the State count in a bar char
StateCount %&gt;% ggplot(aes(x=`State_ABV`,y=`Number of Breweries in State`,fill=State_ABV))+
  geom_bar(stat=&quot;identity&quot;)+
  ggtitle(&quot;Total Amount of Breweries in Each State&quot;)+
  xlab(&quot;State&quot;)+
  ylab(&quot;Total Breweries in a State&quot;)+
  geom_text(aes(State_ABV, StateCount$`Number of Breweries in State` + 2, label = StateCount$`Number of Breweries in State`, fill = NULL))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Answer: Acording to our dataset, there are 558 breweries in the US.</p>
<pre class="r"><code>#Question 2: Merge beer data with breweries data. Print the first 6 observations and the last six observations to check the merged file

##Merging the two datasets into one using a full join
TotalDataSet &lt;- full_join(Beers,Breweries, by = c(&quot;Brewery_id&quot; = &quot;Brew_ID&quot;))
TotalDataSet</code></pre>
<pre><code>## # A tibble: 2,410 x 10
##    Name.x  Beer_ID   ABV   IBU Brewery_id Style  Ounces Name.y  City  State
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;
##  1 Pub Be~    1436 0.05     NA        409 Ameri~     12 10 Bar~ Bend  OR   
##  2 Devil&#39;~    2265 0.066    NA        178 Ameri~     12 18th S~ Gary  IN   
##  3 Rise o~    2264 0.071    NA        178 Ameri~     12 18th S~ Gary  IN   
##  4 Sinist~    2263 0.09     NA        178 Ameri~     12 18th S~ Gary  IN   
##  5 Sex an~    2262 0.075    NA        178 Ameri~     12 18th S~ Gary  IN   
##  6 Black ~    2261 0.077    NA        178 Oatme~     12 18th S~ Gary  IN   
##  7 Lake S~    2260 0.045    NA        178 Ameri~     12 18th S~ Gary  IN   
##  8 Foreman    2259 0.065    NA        178 Ameri~     12 18th S~ Gary  IN   
##  9 Jade       2258 0.055    NA        178 Ameri~     12 18th S~ Gary  IN   
## 10 Cone C~    2131 0.086    NA        178 Ameri~     12 18th S~ Gary  IN   
## # ... with 2,400 more rows</code></pre>
<pre class="r"><code>str(TotalDataSet)</code></pre>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 2410 obs. of  10 variables:
##  $ Name.x    : chr  &quot;Pub Beer&quot; &quot;Devil&#39;s Cup&quot; &quot;Rise of the Phoenix&quot; &quot;Sinister&quot; ...
##  $ Beer_ID   : num  1436 2265 2264 2263 2262 ...
##  $ ABV       : num  0.05 0.066 0.071 0.09 0.075 0.077 0.045 0.065 0.055 0.086 ...
##  $ IBU       : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ Brewery_id: num  409 178 178 178 178 178 178 178 178 178 ...
##  $ Style     : chr  &quot;American Pale Lager&quot; &quot;American Pale Ale (APA)&quot; &quot;American IPA&quot; &quot;American Double / Imperial IPA&quot; ...
##  $ Ounces    : num  12 12 12 12 12 12 12 12 12 12 ...
##  $ Name.y    : chr  &quot;10 Barrel Brewing Company&quot; &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; ...
##  $ City      : chr  &quot;Bend&quot; &quot;Gary&quot; &quot;Gary&quot; &quot;Gary&quot; ...
##  $ State     : chr  &quot;OR&quot; &quot;IN&quot; &quot;IN&quot; &quot;IN&quot; ...</code></pre>
<pre class="r"><code>TotalDataSet$Style = as.factor(TotalDataSet$Style)


##Checking the first and last 6 observations
head(TotalDataSet,n=6)</code></pre>
<pre><code>## # A tibble: 6 x 10
##   Name.x  Beer_ID   ABV   IBU Brewery_id Style   Ounces Name.y  City  State
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;
## 1 Pub Be~    1436 0.05     NA        409 Americ~     12 10 Bar~ Bend  OR   
## 2 Devil&#39;~    2265 0.066    NA        178 Americ~     12 18th S~ Gary  IN   
## 3 Rise o~    2264 0.071    NA        178 Americ~     12 18th S~ Gary  IN   
## 4 Sinist~    2263 0.09     NA        178 Americ~     12 18th S~ Gary  IN   
## 5 Sex an~    2262 0.075    NA        178 Americ~     12 18th S~ Gary  IN   
## 6 Black ~    2261 0.077    NA        178 Oatmea~     12 18th S~ Gary  IN</code></pre>
<pre class="r"><code>tail(TotalDataSet,n=6)</code></pre>
<pre><code>## # A tibble: 6 x 10
##   Name.x   Beer_ID   ABV   IBU Brewery_id Style  Ounces Name.y  City  State
##   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;
## 1 Rocky M~    1035 0.075    NA        425 Ameri~     12 Wynkoo~ Denv~ CO   
## 2 Belgora~     928 0.067    45        425 Belgi~     12 Wynkoo~ Denv~ CO   
## 3 Rail Ya~     807 0.052    NA        425 Ameri~     12 Wynkoo~ Denv~ CO   
## 4 B3K Bla~     620 0.055    NA        425 Schwa~     12 Wynkoo~ Denv~ CO   
## 5 Silverb~     145 0.055    40        425 Ameri~     12 Wynkoo~ Denv~ CO   
## 6 Rail Ya~      84 0.052    NA        425 Ameri~     12 Wynkoo~ Denv~ CO</code></pre>
<p>Answer: I used a full_join function to merge the Beer and Brewery data sets.</p>
<pre class="r"><code>#Question 3: Address the missing values in each column

##Show name of columns with missing data
names(which(colSums(is.na(TotalDataSet))&gt;0))</code></pre>
<pre><code>## [1] &quot;ABV&quot;   &quot;IBU&quot;   &quot;Style&quot;</code></pre>
<p>Answer: The missing values in ABV and IBU will be dropped using na.rm = TRUE equation or I will all the missing values to natural be ignored during aggregation calculations. To perform k-NN classfication models, I will delete all the observations with missing values using the na.omit() function.</p>
<pre class="r"><code>#Question 4: Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.

##Calculation of State median ABVs and IBUs
State_Medians_for_ABV_IBU &lt;- TotalDataSet %&gt;% 
  group_by(State) %&gt;% 
  summarize(count=n(),
    Median_ABV=median(ABV,na.rm=TRUE),
    Median_IBU=median(IBU,na.rm = TRUE))

arrange(State_Medians_for_ABV_IBU,desc(Median_IBU))</code></pre>
<pre><code>## # A tibble: 51 x 4
##    State count Median_ABV Median_IBU
##    &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 ME       27     0.051        61  
##  2 WV        2     0.062        57.5
##  3 FL       58     0.057        55  
##  4 GA       16     0.055        55  
##  5 DE        2     0.055        52  
##  6 NM       14     0.062        51  
##  7 NH        8     0.055        48.5
##  8 DC        8     0.0625       47.5
##  9 NY       74     0.055        47  
## 10 AK       25     0.056        46  
## # ... with 41 more rows</code></pre>
<pre class="r"><code>arrange(State_Medians_for_ABV_IBU,desc(Median_ABV))</code></pre>
<pre><code>## # A tibble: 51 x 4
##    State count Median_ABV Median_IBU
##    &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 DC        8     0.0625       47.5
##  2 KY       21     0.0625       31.5
##  3 MI      162     0.062        35  
##  4 NM       14     0.062        51  
##  5 WV        2     0.062        57.5
##  6 CO      265     0.0605       40  
##  7 AL       10     0.06         43  
##  8 CT       27     0.06         29  
##  9 NV       11     0.06         41  
## 10 OK       19     0.06         35  
## # ... with 41 more rows</code></pre>
<pre class="r"><code>##Bar chart to plot the State median IBUs
State_Medians_for_ABV_IBU %&gt;% ggplot(aes(x=State, y=Median_IBU, fill=State))+
  geom_bar(stat = &quot;identity&quot;)+
  ggtitle(&quot;Median IBU of Each State&quot;)+
  ylab(&quot;Median International Bitterness Units of the Beer (IBU)&quot;)+
  theme(axis.text.x = element_text(angle = 90))</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (position_stack).</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>##Bar chart to plot the State median ABV
State_Medians_for_ABV_IBU %&gt;% ggplot(aes(x=State, y=Median_ABV,fill=State))+
  geom_bar(stat = &quot;identity&quot;)+
  ggtitle(&quot;Median ABV of Each State&quot;)+
  ylab(&quot;Median International Bitterness Units of the Beer (IBU)&quot;)+
  theme(axis.text.x = element_text(angle = 90))</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p>Comment: Based on the barchart visualization, Maine has the highest median IBU followed by West Virginia.</p>
<pre class="r"><code>#Question 5: Which state has the maximum alcoholic (ABV) beer? Which State has the most bitter (IBU) beer?

##Use which.max () to find the state with max ABV and IBU

TotalDataSet[which.max(TotalDataSet$ABV),]</code></pre>
<pre><code>## # A tibble: 1 x 10
##   Name.x    Beer_ID   ABV   IBU Brewery_id Style  Ounces Name.y City  State
##   &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;
## 1 Lee Hill~    2565 0.128    NA         52 Quadr~   19.2 Upslo~ Boul~ CO</code></pre>
<pre class="r"><code>TotalDataSet[which.max(TotalDataSet$IBU),]</code></pre>
<pre><code>## # A tibble: 1 x 10
##   Name.x   Beer_ID   ABV   IBU Brewery_id Style  Ounces Name.y  City  State
##   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;
## 1 Bitter ~     980 0.082   138        375 Ameri~     12 Astori~ Asto~ OR</code></pre>
<pre class="r"><code>TotalDataSet %&gt;% drop_na() %&gt;% ggplot(aes(y=IBU))+geom_boxplot(fill=&quot;Red&quot;)+
  ggtitle(&quot;Boxplot of International Bitterness of the Beer (IBU)&quot;)</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Answer:</p>
<p>Colorado has the beer with the highest ABV content: Lee Hill Series Vol. 5 - Belgian STyle Quadrupel Ale (12.8% ABV) from the Upslope Brewing Company.</p>
<p>Oregon has the beer with the highest IBU content: Bitter Bitch Imperial IPA (IBU of 138) from the Astoria Brewing Company</p>
<pre class="r"><code>#Question 6 : Comment on the summary statistics and distribution of the ABV variable.

##View the statistical summary of the ABV column in TotalDataSet
summary(TotalDataSet$ABV,digits = 3)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##  0.0010  0.0500  0.0560  0.0598  0.0670  0.1280      62</code></pre>
<pre class="r"><code>##View the statistical summary of the IBU column in TotalDataSet
summary(TotalDataSet$IBU, digits = 3)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##     4.0    21.0    35.0    42.7    64.0   138.0    1005</code></pre>
<pre class="r"><code>##ABV boxplot 
TotalDataSet %&gt;% drop_na() %&gt;% ggplot(aes(y=ABV))+geom_boxplot(fill=&quot;blue&quot;)+
  ggtitle(&quot;Boxplot of Alcohol by Volume of the Beer (ABV)&quot;)</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>##IBU boxplot 
TotalDataSet %&gt;% drop_na() %&gt;% ggplot(aes(y=IBU))+geom_boxplot(fill=&quot;Red&quot;)+
  ggtitle(&quot;Boxplot of International Bitterness of the Beer (IBU)&quot;)</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<pre class="r"><code>##ABV histogram of stat summary
TotalDataSet %&gt;% ggplot(aes(x=ABV))+geom_histogram(fill=&quot;Red&quot;)+
  ggtitle(&quot;Histogram of Alcohol by Volume of the Beer (ABV)&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 62 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-9-3.png" width="672" /></p>
<pre class="r"><code>##IBU histogram of stat summary
TotalDataSet %&gt;% ggplot(aes(x=IBU))+geom_histogram(fill=&quot;Red&quot;)+
  ggtitle(&quot;Histogram of International Bitterness of the Beer (IBU)&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1005 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-9-4.png" width="672" /></p>
<p>Answer: There appears to be some right-skewness in the ABV distribution based on its histogram, which could be from the influence of higher ABVs on the group’s mean. This is further supported by the large range from the data set; 0.001(min) to 0.128(max) and the mean being greater than the median.</p>
<pre class="r"><code>#Question 7: Is there an apparent relationship between the bitterness of the beer and its alcoholic content?


Beers %&gt;% drop_na() %&gt;% ggplot(aes(x=ABV, y=IBU))+
  geom_smooth(se=FALSE,color=&quot;red&quot;)+
  ggtitle(&quot;ABV to IBU Covariation Analysis&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Answer: There appears to be a positive correlation of ABV to IBU (maybe some type of polynomial relationship); an increase in the amount of alcohol in a beer appears to correlate with the beer becoming more bitter.</p>
<pre class="r"><code>#Question 8: Budweiser would like to investigative the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with &quot;Ale&quot; in its name other than IPA)

##Filter TotalDataSet for &quot;Ale&quot; only beer styles to create a Ale only data set
All_Ale &lt;- filter(TotalDataSet, grepl(&quot;Ale&quot;, Style))
Only_Ale &lt;- filter(All_Ale, !grepl(&quot;IPA&quot;,Style)) #Removes remaining observations with &quot;IPA&quot; in their style
Only_Ale$Style = &quot;Ale&quot;

##Show statistical summary for Ale only style beers
summary(Only_Ale)</code></pre>
<pre><code>##     Name.x             Beer_ID            ABV               IBU        
##  Length:963         Min.   :   1.0   Min.   :0.03500   Min.   :  4.00  
##  Class :character   1st Qu.: 756.5   1st Qu.:0.05000   1st Qu.: 20.00  
##  Mode  :character   Median :1350.0   Median :0.05500   Median : 30.00  
##                     Mean   :1378.0   Mean   :0.05681   Mean   : 34.33  
##                     3rd Qu.:2053.5   3rd Qu.:0.06000   3rd Qu.: 44.25  
##                     Max.   :2690.0   Max.   :0.09900   Max.   :115.00  
##                                      NA&#39;s   :31        NA&#39;s   :411     
##    Brewery_id       Style               Ounces         Name.y         
##  Min.   :  1.0   Length:963         Min.   :12.00   Length:963        
##  1st Qu.: 93.0   Class :character   1st Qu.:12.00   Class :character  
##  Median :205.0   Mode  :character   Median :12.00   Mode  :character  
##  Mean   :235.9                      Mean   :13.47                     
##  3rd Qu.:369.0                      3rd Qu.:16.00                     
##  Max.   :558.0                      Max.   :32.00                     
##                                                                       
##      City              State          
##  Length:963         Length:963        
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
##                                       
## </code></pre>
<pre class="r"><code>##Filter to create an &quot;IPA&quot; only data set
IPA &lt;- filter(TotalDataSet, grepl(&quot;IPA&quot;,Style))
IPA$Style = &quot;IPA&quot;


##Show statistical summary for IPA only style beers
summary(IPA)</code></pre>
<pre><code>##     Name.x             Beer_ID          ABV               IBU        
##  Length:571         Min.   :   4   Min.   :0.02700   Min.   : 30.00  
##  Class :character   1st Qu.: 868   1st Qu.:0.06200   1st Qu.: 60.00  
##  Mode  :character   Median :1603   Median :0.06800   Median : 70.00  
##                     Mean   :1494   Mean   :0.06879   Mean   : 71.95  
##                     3rd Qu.:2089   3rd Qu.:0.07500   3rd Qu.: 85.00  
##                     Max.   :2692   Max.   :0.09900   Max.   :138.00  
##                                    NA&#39;s   :11        NA&#39;s   :179     
##    Brewery_id       Style               Ounces         Name.y         
##  Min.   :  1.0   Length:571         Min.   :12.00   Length:571        
##  1st Qu.: 87.5   Class :character   1st Qu.:12.00   Class :character  
##  Median :206.0   Mode  :character   Median :12.00   Mode  :character  
##  Mean   :224.8                      Mean   :13.75                     
##  3rd Qu.:344.5                      3rd Qu.:16.00                     
##  Max.   :557.0                      Max.   :32.00                     
##                                                                       
##      City              State          
##  Length:571         Length:571        
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
##                                       
## </code></pre>
<pre class="r"><code>##Combine the IPA and Ale only data sets
IPA_and_Only_Ale_Comb &lt;- rbind(IPA,Only_Ale)
str(IPA_and_Only_Ale_Comb)</code></pre>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 1534 obs. of  10 variables:
##  $ Name.x    : chr  &quot;Rise of the Phoenix&quot; &quot;Sinister&quot; &quot;Sex and Candy&quot; &quot;Cone Crusher&quot; ...
##  $ Beer_ID   : num  2264 2263 2262 2131 1980 ...
##  $ ABV       : num  0.071 0.09 0.075 0.086 0.085 0.07 0.07 0.07 0.097 0.07 ...
##  $ IBU       : num  NA NA NA NA NA 70 70 70 94 65 ...
##  $ Brewery_id: num  178 178 178 178 178 369 369 369 369 369 ...
##  $ Style     : chr  &quot;IPA&quot; &quot;IPA&quot; &quot;IPA&quot; &quot;IPA&quot; ...
##  $ Ounces    : num  12 12 12 12 12 12 12 12 12 12 ...
##  $ Name.y    : chr  &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; ...
##  $ City      : chr  &quot;Gary&quot; &quot;Gary&quot; &quot;Gary&quot; &quot;Gary&quot; ...
##  $ State     : chr  &quot;IN&quot; &quot;IN&quot; &quot;IN&quot; &quot;IN&quot; ...</code></pre>
<pre class="r"><code>##Delete all missing observations, and rename State column to &quot;STATE_ABBV&quot;
CleanData_IPA_and_Ale &lt;- na.omit(IPA_and_Only_Ale_Comb)
##Change column name to &quot;STATE_ABBV&quot;
colnames(CleanData_IPA_and_Ale)[10] = &quot;STATE_ABBV&quot;


##Scatterplot of Ale&#39;s and IPA&#39;s relationship between IBU and ABV
CleanData_IPA_and_Ale %&gt;% ggplot(aes(x=ABV, y=IBU, color= Style))+
  geom_smooth(aes(linetype = Style),se=FALSE)+
  ggtitle(&quot;Covariation of IBU and ABV for Ale and IPA Beers Only&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Comment: The same positive correlation also appears in beers that are only “Ale” and “IPA”. The chart shows the visual relationship of IPAs having a higher median ABV of 6.8% and IBU of 70 compared to Ales median ABV of 5.5% and IBU of 30. There are 963 Ales and 571 IPAs in the data set; the two largest “styles” of beer brewed.</p>
<pre class="r"><code>#Question 8 (cont.): Budweiser would like to investigative the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with &quot;Ale&quot; in its name other than IPA)

##Tells the percentage of the dataset that will go into the training set
splitPerc = .75

##Searching for the best k by looping for many k and the average of many training / test partition 

iterations = 500
numks = 30

masterAcc = matrix(nrow = iterations, ncol = numks)
  
for(j in 1:iterations)
{
accs = data.frame(accuracy = numeric(30), k = numeric(30))
trainIndices = sample(1:dim(CleanData_IPA_and_Ale)[1],round(splitPerc * dim(CleanData_IPA_and_Ale)[1]))
train = CleanData_IPA_and_Ale[trainIndices,]
test = CleanData_IPA_and_Ale[-trainIndices,]
for(i in 1:numks)
{
  classifications = knn(train[,c(3,4)],test[,c(3,4)],train$Style, prob = TRUE, k = i)
  table(classifications,test$Style)
  CM = confusionMatrix(table(classifications,test$Style))
  masterAcc[j,i] = CM$overall[1]
}

}

MeanAcc = colMeans(masterAcc)

##Plot the outcome
plot(seq(1,numks,1),MeanAcc, type = &quot;l&quot;)</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>##Standardizing my explanatory variables
Standard_CleanData_IPA_and_Ale &lt;- data.frame(ZABV = scale(CleanData_IPA_and_Ale$ABV),
      ZIBU = scale(CleanData_IPA_and_Ale$IBU), 
      Style = CleanData_IPA_and_Ale$Style)

StandardtrainIndices = sample(1:dim(Standard_CleanData_IPA_and_Ale)[1],round(splitPerc * dim(Standard_CleanData_IPA_and_Ale)[1]))
Standard_train = Standard_CleanData_IPA_and_Ale[StandardtrainIndices,]
Standard_test = Standard_CleanData_IPA_and_Ale[-StandardtrainIndices,]

##External Validation, k=5, unstandardized

classifications = knn(train[,c(3,4)],test[,c(3,4)],train$Style, prob = TRUE, k=5)
table(classifications,test$Style)
confusionMatrix(table(classifications,test$Style))

##External Validation, k=5, Standardized
classifications = knn(Standard_train[,c(1,2)],Standard_test[,c(1,2)],Standard_train$Style, prob = TRUE, k=5)
table(classifications,Standard_test$Style)
confusionMatrix(table(classifications,Standard_test$Style))

##Change Style to a factor
CleanData_IPA_and_Ale$Style=as.factor(CleanData_IPA_and_Ale$Style)

##Internal cross Validation, unstandardized with k=3
classifications = knn.cv(CleanData_IPA_and_Ale[,c(3,4)], CleanData_IPA_and_Ale$Style, k = 3)
data.frame(classifications = classifications, true = CleanData_IPA_and_Ale$Style)
confusionMatrix(classifications,CleanData_IPA_and_Ale$Style)

##Internal cross Validation, standardized with k = 3
classifications = knn.cv(Standard_CleanData_IPA_and_Ale[,c(1,2)],Standard_CleanData_IPA_and_Ale$Style, k=3)
data.frame(classifications = classifications, true = Standard_CleanData_IPA_and_Ale$Style)
confusionMatrix(classifications,Standard_CleanData_IPA_and_Ale$Style)


##Internal cross Validation, unstandardized with k=5
classifications = knn.cv(CleanData_IPA_and_Ale[,c(3,4)], CleanData_IPA_and_Ale$Style, k = 5)
data.frame(classifications = classifications, true = CleanData_IPA_and_Ale$Style)
confusionMatrix(classifications,CleanData_IPA_and_Ale$Style)

##Internal cross Validation, standardized with k = 5
classifications = knn.cv(Standard_CleanData_IPA_and_Ale[,c(1,2)],Standard_CleanData_IPA_and_Ale$Style, k=5)
data.frame(classifications = classifications, true = Standard_CleanData_IPA_and_Ale$Style)
confusionMatrix(classifications,Standard_CleanData_IPA_and_Ale$Style)</code></pre>
<p>Comment: Our search for the best k by looping for many k and the average of many training / test partition recommends knn = 5 or 6, we will use 5. From the internal/external, standardized/unstandardized k-NN classification models I ran, the untandardized internal k=5 model delivered the highest accuracy; I was able to accuracy identify an IPA or an Ale with 86.65% accuracy.</p>
<pre class="r"><code>#Question 9: Find one other useful inference from the data that Budweiser may be able to find value in. 

##Import Household Median Income Data for 2019
PerState_Data &lt;- read.csv(&quot;C:/Users/Antonio Debouse/Desktop/Doing Data Science/GitHub/Budweiser-Case-Study/Budweiser Case Study/State Population Data.csv&quot;,na=&quot;.&quot;)
str(PerState_Data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    51 obs. of  6 variables:
##  $ State            : Factor w/ 51 levels &quot;alabama&quot;,&quot;alaska &quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ STATE_ABV        : Factor w/ 51 levels &quot;AK&quot;,&quot;AL&quot;,&quot;AR&quot;,..: 2 1 4 3 5 6 7 9 8 10 ...
##  $ REGION           : Factor w/ 6 levels &quot;Midwest&quot;,&quot;Northeast&quot;,..: 4 3 5 4 6 6 2 4 2 4 ...
##  $ Population       : int  4850771 738565 6809946 2977944 38982847 5436519 3594478 943732 672391 20278447 ...
##  $ Med_Household_Inc: int  46472 76114 53510 43813 67169 65458 73781 63036 77649 50883 ...
##  $ Beer_Consump     : num  28.9 26 26.6 23.7 25.1 28.3 20.2 28.7 NA 26.3 ...</code></pre>
<pre class="r"><code>PerState_Data$State = as.character(PerState_Data$State)
PerState_Data$STATE_ABV = as.character(PerState_Data$STATE_ABV)
###Beer consumption column is per capita
###Source: U.S. Census Bureau, 2017 American Community Survey and 2017 Puerto Rico Community Surveys.       


##Create IPACount and AlCount data 
IPACountPerState &lt;- count(IPA,IPA$State)
AleCountPerState &lt;- count(Only_Ale,Only_Ale$State)

##Add IPACount per count State to StateCount data set
countA &lt;- full_join(StateCount,IPACountPerState,by=c(&quot;State_ABV&quot;= &quot;IPA$State&quot;))
#Add AleCount per State to StateCount data set
countB &lt;- full_join(countA,AleCountPerState,by=c(&quot;State_ABV&quot;=&quot;Only_Ale$State&quot;))
##Replace missing values with )
countB[is.na(countB)] &lt;-0

##rename columns
colnames(countB)[3]=&quot;IPACount_per_State&quot;
colnames(countB)[4]=&quot;AleCount_per_State&quot;

##adding breweries per state to PerState data
Count_PerState_Data &lt;- inner_join(PerState_Data,countB,by=c(&quot;STATE_ABV&quot;=&quot;State_ABV&quot;))


##Plot correlation matrix
plot_correlation(na.omit(Count_PerState_Data[,c(3:9)]), type = &quot;all&quot;,&#39;Review.Date&#39;)</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>#Get the rank of variables based on regions

view(Count_PerState_Data %&gt;% group_by(REGION) %&gt;% summarize(
  MedianPopulation = median(Population),
  Median_House_Inc = median(Med_Household_Inc),
  Median_Beer_Consump = median(Beer_Consump,na.rm = TRUE),
  Median_Num_Breweries = sum(`Number of Breweries in State`,na.rm = TRUE)) %&gt;%
  mutate(Beer_Consunp_Rank = rank(-Median_Beer_Consump, ties.method = &quot;first&quot;),
    PopRank = rank(-MedianPopulation, ties.method = &quot;first&quot;),
         House_Inc_Rank = rank(-Median_House_Inc,ties.method = &quot;first&quot;),
         Rank_Num_Breweries = rank(-Median_Num_Breweries)))</code></pre>
<p>Comment:</p>
<p>If we assume the ideal location for expansion is in a region with one of the highest beer consumptions, then using a correlation model we see the strongest positive relationship to beer consumption is with the Midwest region. The Midwest has the highest median population, the second highest median beer consumption and second most amount of breweries will also having the 4th highest median household income during 2017.</p>
<p>Even though the West region had the most breweries and highest median beer consumption, it was only had the 4th highest median population and third median household income. This lead to hypothesis that real estate and/or breweries would on average be cheaper leading to better value to focus expansion resources; however, further analysis is need to test my assumptions.</p>
<pre class="r"><code>#Create a data set to combine all &quot;styles&quot; counts per state to one data frame

##Analysis the number of Styles in the total data set, then chose familar styles as main categories
str(TotalDataSet$Style)</code></pre>
<pre><code>##  Factor w/ 99 levels &quot;Abbey Single Ale&quot;,..: 18 17 15 11 15 79 17 21 17 11 ...</code></pre>
<pre class="r"><code>##Filter to create an &quot;Cider&quot; only data set
Cider &lt;- filter(TotalDataSet, grepl(&quot;Cider&quot;,Style))
Cider$Style = &quot;Cider&quot;

##Filter to create an &quot;Stout&quot; only data set
Stout &lt;- filter(TotalDataSet, grepl(&quot;Stout&quot;,Style))
Stout$Style = &quot;Stout&quot;

##Filter to create an &quot;Stout&quot; only data set
Porter &lt;- filter(TotalDataSet, grepl(&quot;Porter&quot;,Style))
Porter$Style = &quot;Porter&quot;

##Filter to create an &quot;Lager&quot; only data set
Lager &lt;- filter(TotalDataSet, grepl(&quot;Lager&quot;,Style))
Lager$Style = &quot;Lager&quot;

##Filter to create an &quot;Lager&quot; only data set
Pilsener &lt;- filter(TotalDataSet, grepl(&quot;Pilsener&quot;,Style))
Pilsener$Style = &quot;German or Czech Pilsener&quot;

#Filter to create a &quot;Pilsner&quot; only data set
Pilsner &lt;- filter(TotalDataSet, grepl(&quot;Pilsner&quot;, Style))
Pilsner$Style = &quot;American Pilsner&quot;

#Filter to create &quot;Fruit Beer&quot; only data set
Fruit_Beer &lt;- filter(TotalDataSet, grepl(&quot;Fruit&quot;, Style))
Fruit_Beer$Style = &quot;Fruity Beer&quot;

##Filter to create an &quot;Other&quot; sytles of beer only data set
Other_Styles &lt;- filter(TotalDataSet, !grepl(&quot;Ale&quot;,Style),!grepl(&quot;IPA&quot;,Style),!grepl(&quot;Cider&quot;, Style),!grepl(&quot;Stout&quot;, Style),!grepl(&quot;Porter&quot;,Style),!grepl(&quot;Lager&quot;,Style), !grepl(&quot;Pilsener&quot;,Style), !grepl(&quot;Pilsner&quot;, Style), !grepl(&quot;Fruit&quot;, Style))

Other_Styles$Style &lt;- &quot;Other Styles&quot;


##Combine all &quot;styles&quot; into one data set
ALL_Styles_Category &lt;- rbind(IPA,Only_Ale,Cider,Stout,Porter,Lager,Pilsener,Pilsner,Fruit_Beer,Other_Styles)

str(ALL_Styles_Category)</code></pre>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 2410 obs. of  10 variables:
##  $ Name.x    : chr  &quot;Rise of the Phoenix&quot; &quot;Sinister&quot; &quot;Sex and Candy&quot; &quot;Cone Crusher&quot; ...
##  $ Beer_ID   : num  2264 2263 2262 2131 1980 ...
##  $ ABV       : num  0.071 0.09 0.075 0.086 0.085 0.07 0.07 0.07 0.097 0.07 ...
##  $ IBU       : num  NA NA NA NA NA 70 70 70 94 65 ...
##  $ Brewery_id: num  178 178 178 178 178 369 369 369 369 369 ...
##  $ Style     : chr  &quot;IPA&quot; &quot;IPA&quot; &quot;IPA&quot; &quot;IPA&quot; ...
##  $ Ounces    : num  12 12 12 12 12 12 12 12 12 12 ...
##  $ Name.y    : chr  &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; &quot;18th Street Brewery&quot; ...
##  $ City      : chr  &quot;Gary&quot; &quot;Gary&quot; &quot;Gary&quot; &quot;Gary&quot; ...
##  $ State     : chr  &quot;IN&quot; &quot;IN&quot; &quot;IN&quot; &quot;IN&quot; ...</code></pre>
<pre class="r"><code>##Change Style and State variables to factors
ALL_Styles_Category$Style = as.factor(ALL_Styles_Category$Style)
ALL_Styles_Category$State = as.factor(ALL_Styles_Category$State)

colnames(ALL_Styles_Category)[1]=&quot;Names of Beers&quot;
colnames(ALL_Styles_Category)[8] = &quot;Names of Breweries&quot;

#Plot Barchart with count of beers in each state, fill with style catergories
ALL_Styles_Category %&gt;% ggplot(aes(x=State, fill = Style))+
  geom_bar()+  ggtitle(&quot;Total Beers Brewed in Each State, Coded by Beer Type&quot;)+
  xlab(&quot;State&quot;)+
  ylab(&quot;Total Beers Brewed in a State&quot;)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))</code></pre>
<p><img src="Budwesier-Case-Study_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>summary(ALL_Styles_Category[,6])</code></pre>
<pre><code>##           Style    
##  Ale         :963  
##  IPA         :571  
##  Other Styles:367  
##  Lager       :158  
##  Stout       :100  
##  Porter      : 74  
##  (Other)     :177</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
